Clustering Resume/Clustering Resume/article/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleCreateUpdateView, ArticleDeleteView
from . import views

urlpatterns = [
    path('', ArticleListView.as_view()),  # 리스트
    path('create/', ArticleCreateUpdateView.as_view()),  # 게시물 작성
    path('<article_id>/', ArticleDetailView.as_view()),  # 상세페이지
    path('<article_id>/update/', ArticleCreateUpdateView.as_view()),  # 게시물 업데이트
    path('<article_id>/delete/', ArticleDeleteView.as_view()),
]

Clustering Resume/Clustering Resume/bot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chatbot, name='chatbot'),
    path('cam', views.chatbot_cam, name='chatbot_cam'),
    path('bot', views.bot, name='bot'),
    path('stopwatch', views.stopwatch, name='bot'),
    path('button_real', views.button_real, name='bot'),
    path('gan', views.gan, name='bot'),
    path('logo', views.logo, name='bot'),
    path('mirime', views.mirime, name='bot'),
    path('bottom', views.bottom, name='bot'),
    path('soundwave', views.soundwave, name='bot'),
    path('/home/mypage/', views.mypage, name="mypage"),
]

Clustering Resume/Clustering Resume/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('details/', views.details, name="details"),
   # path('details-basic/', views.detailsBasic, name="courseDetailsBasic"),
   #  path('list/', views.list, name="list"),
   #  path('listlist/', views.listlist, name="list"),
    path('mypage/', views.mypage, name="mypage"),
    path('result_list/', views.result_list, name="result_list"),
    # path('result_list/<resumes.id>', views.result_details, name="result_details"),
    # path('result_details/<resumes.id>/listlist', views.listlist, name="listlist"),
]

Clustering Resume/Clustering Resume/article/models.py
from django.db import models
#from docx import Document

class Article(models.Model):
    title = models.CharField('제목', max_length=126, null=False)
    content = models.TextField('내용', null=False)
    author = models.CharField('작성자', max_length=16, null=False)
    created_at = models.DateTimeField('작성일', auto_now_add=True)
    #created_at.editable = True  # created의 editable 속성에 True를 설정했습니다.

    def __str__(self):
        return '[{}] {}'.format(self.id, self.title)

Clustering Resume/Clustering Resume/article/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label= 'Select a file',
        help_text = 'max. 42 megabytes'
    )

Clustering Resume/Clustering Resume/article/views.py
from django.http import HttpResponse, Http404
from django.views.generic import TemplateView
from .models import Article
from django.http import HttpResponseRedirect
from django.contrib import messages

def deleteContent(request):
    delData = Article.objects.get(pk=request.GET.get("pk"))
    delData.delete()
    return HttpResponseRedirect("/article/")

class ArticleListView(TemplateView):
    template_name = 'article_list.html'

    def get(self, request, *args, **kwargs):
        print(request.GET)
        queryset = Article.objects.all()
        ctx = {
            'articles': queryset
        }
        return self.render_to_response(ctx)

class ArticleDetailView(TemplateView):
    template_name = 'article_detail.html'
    queryset = Article.objects.all()
    pk_url_kwargs = 'article_id'

    def get_object(self, queryset=None):
        queryset = queryset or self.queryset
        pk = self.kwargs.get(self.pk_url_kwargs)
        article = queryset.filter(pk=pk).first()

        if not article:
            raise Http404('invalid pk')
        return article

    def get(self, request, *args, **kwargs):
        article = self.get_object()

        ctx = {
            'article': article
        }
        return self.render_to_response(ctx)


class ArticleCreateUpdateView(TemplateView):
    template_name = 'article_update.html'
    queryset = Article.objects.all()
    pk_url_kwargs = 'article_id'

    def get_object(self, queryset=None):
        queryset = queryset or self.queryset
        pk = self.kwargs.get(self.pk_url_kwargs)
        article = queryset.filter(pk=pk).first()

        if pk and not article:
            raise Http404('invalid pk')
        return article

    def get(self, request, *args, **kwargs):
        article = self.get_object()

        ctx = {
            'article': article,
        }
        return self.render_to_response(ctx)

    def post(self, request, *args, **kwargs):
        action = request.POST.get('action')
        post_data = {key: request.POST.get(key) for key in ('title', 'content', 'author')}
        for key in post_data:
            if not post_data[key]:
                messages.error(self.request, '{} 값이 존재하지 않습니다.'.format(key), extra_tags='danger')

        if len(messages.get_messages(request)) == 0:
            if action == 'create':
                article = Article.objects.create(**post_data)
                messages.success(self.request, '게시글이 저장되었습니다.')
            elif action == 'update':
                article = self.get_object()
                for key, value in post_data.items():
                    setattr(article, key, value)
                article.save()
                messages.success(self.request, '게시글이 수정되었습니다.')
            else:
                messages.error(self.request, '알 수 없는 요청입니다.', extra_tags='danger')

            return HttpResponseRedirect('/article/') # 정상적인 저장이 완료되면 '/articles/'로 이동됨

        ctx = {
            'article': self.get_object() if action == 'update' else None
        }
        return self.render_to_response(ctx)


class ArticleDeleteView(TemplateView):
    template_name = 'article_list.html'
    queryset = Article.objects.all()
    pk_url_kwargs = 'article_id'

    def remove(self, request, pk):
        article = self.get_object(pk=pk)
        if request.method == 'POST':
            article.delete()
            messages.success(self.request, '게시글이 삭제되었습니다.')
            return HttpResponseRedirect('/article/')
        else:
            messages.error(self.request, '알 수 없는 요청입니다.', extra_tags='danger')

        return HttpResponseRedirect('/article/')  # 정상적인 저장이 완료되면 '/articles/'로 이동됨

Clustering Resume/Clustering Resume/article/templates/article_detail.html
<script type="text/javascript">
	function deleteRequest(pk){
	    	var answer=confirm("정말 삭제하시겠습니까?")
	    	if(answer){
		    	location.href="/delete/"+pk
		    	alert("정상적으로 삭제되었습니다.")
	    	}
	}
</script>
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}면접챗봇 | 자기소개서기반 모의면접{% endblock %}
{% block description %}<meta name="description" content="자기소개서를 기반으로 질문을 하는 면접챗봇입니다.">{% endblock %}
{% block content %}
<head>
    <style>
        .dropdown .nav-link{
  border: none;
  outline: none;
  background-color: inherit;
  margin: 0;
}
.dropdown-content {
  display: none;
  position: absolute;
  background-color: white;
  min-width: 120px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  font-size : 14px;
  float: none;
  color: black;
  padding: 8px 4px;
  display: block;
  text-align: left;
    border-bottom: 1px solid  black;
}
.dropdown-content a:hover {
  color:#fdc632;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.button {
  width: 25%;
  height: 45px;
  font-family: 'Roboto', sans-serif;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2.5px;
  font-weight: 500;
  color: #fff;
  background-color: #79a4d2;
  border: none;
  border-radius: 45px;
  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease 0s;
  cursor: pointer;
  outline: none;
  }

.button:hover {
  background-color: white;
  box-shadow: 0px 15px 20px rgba(121,164,210, 0.4);
  color: #000;
  transform: translateY(-7px);
}
th{color:black;}
#finally3 {background: #79a4d2; color: white; border: #79a4d2;}
#finally3:hover {background:white; color:#79a4d2; border: 1px solid #79a4d2;}
    </style>

     <script language="javascript">
   function popupDetail(){
        alert("로그아웃 되었습니다.");
        }
  </script>
</head>
 <header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="{% url 'home:homePage' %}"><img src="{% static 'img/mirime.png' %}" alt="" /></a>
          <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">

               <!-- 변경 -->
                  <li class="nav-item">
                        {% if not request.user.is_authenticated %}
                        <a class="nav-link" href="/user/create/">가입하기</a>
                        {% endif %}
                  </li>
                  <li class="nav-item">
                        {% if user.is_active %}
                        <div class="dropdown">
                          <a class="nav-link" href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <i class="fa fa-caret-down"></i>
                        <div class="dropdown-content">
                          <a href="/resume/">자기소개서 입력</a>
                            <a href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <a href="{% url 'mbti_test' %}">MBTI 검사하기</a>
                          <a href="{% url 'home:result_list' %}">면접결과 보기</a>
                           <a id="button" href="/user/logout/" onclick="popupDetail();">로그아웃</a>
                        </div>
                       </div>
                         <li class="nav-item">
                  <a class="nav-link" href="/bot/">면접 진행하기</a>
                </li>
                        {% else %}
                        <a class="nav-link" href="/user/login/">로그인</a>
                        {% endif %}
                  </li>
                  <!-- 변경 -->

                <li class="nav-item">
                  <a class="nav-link" href="/home/#thebookclub">면접챗봇이란?</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:details' %}">상세정보</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/home/#reviewArea">면접후기</a>
                </li>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/article/">게시판</a>
                </li>
<!--                <li class="nav-item">-->
<!--                  <a class="nav-link" href="/resume/">자기소개서입력</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a class="nav-link" href="/bot/">면접 진행하기</a>-->
<!--                </li>-->
              </ul>
            </div>
        </div>
      </nav>
    </div>
  </header>
  <!--================Home Banner Area =================-->
  <section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <div class="banner_content text-center"><br><br><br>
              <h1>Review & Sharing</h1>
              <div class="page_link">
                <a href="#">생생한 면접 후기와 노하우를 공유하세요!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Home Banner Area =================-->

  <!--================ Start Course Details Area =================-->
  <section class="course_details_area section_gap">
    <div class="container">
{% block css %}
{% endblock css %}

<table class="table table-striped table-bordered">
	<tr>
		<th>번호</th>
		<td>{{ article.pk }}</td>
	</tr>
	<tr>
		<th>제목</th>
		<td>{{ article.title }}</td>
	</tr>
	<tr>
		<th>내용</th>
		<td>{{ article.content | linebreaksbr }}</td>
	</tr>
    <tr>
		<th>작성자</th>
		<td>{{ article.author }}</td>
	</tr>
    <tr>
		<th>작성일</th>
		<td>{{ article.created_at | date:"Y-m-d H:i" }}</td>
	</tr>
</table>

<a href="/article/{{ article.pk }}/update/"><button class="button" type="button">게시글 수정</button></a>
<a href="/article/"><button class="button" type="button">목록으로</button></a>
<!--<a href="/article/{{ article.pk }}/delete/"><button class="btn btn-primary" type="button" style="background-color:#79a4d2;">삭제하기</button></a>-->
<input type="button" class="button" value="글 삭제하기" onclick="deleteRequest('{{article.pk}}')">

                  </div>
 <div class="float-event lvTest" id="testFab">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="my-float">자신의 개성이 반영된 자기소개서입력 완료!<br> 이제 면접만 남았다면 지금 바로 면접을 진행해 보세요!</p>
        </div>
        <div class="col">
          <a href="/bot/"><button class="event-btn" id="finally3" style="margin-top: 16px;" >면접 진행하기</button>
        </div>
      </div>
    </div>
  </div>
  </section>
  <!--================ End Course Details Area =================-->
{% endblock %}

Clustering Resume/Clustering Resume/article/templates/article_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}면접챗봇 | 자기소개서기반 모의면접{% endblock %}
{% block description %}<meta name="description" content="자기소개서를 기반으로 질문을 하는 면접챗봇입니다.">{% endblock %}
{% block content %}
<head>
    <style>
 .dropdown .nav-link{
  border: none;
  outline: none;
  background-color: inherit;
  margin: 0;
}
.dropdown-content {
  display: none;
  position: absolute;
  background-color: white;
  min-width: 120px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  font-size : 14px;
  float: none;
  color: black;
  padding: 8px 4px;
  display: block;
  text-align: left;
    border-bottom: 1px solid  black;
}
.dropdown-content a:hover {
  color:#fdc632;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.btn btn-primary :hover {
    background-color: #3e8e41;
 }

.btn btn-primary {
    background-color : #79a4d2;
}
.button{
margin-left: 330px;
  width: 40%;
  height: 45px;
  font-family: 'Roboto', sans-serif;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2.5px;
  font-weight: 500;
  color: #fff;
  background-color: #79a4d2;
  border: none;
  border-radius: 45px;
  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease 0s;
  cursor: pointer;
  outline: none;
  }

.button:hover {
  background-color: white;
  box-shadow: 0px 15px 20px rgba(121,164,210, 0.4);
  color: #000;
  transform: translateY(-7px);
}
#finally3 {background: #79a4d2; color: white; border: #79a4d2;}
#finally3:hover {background:white; color:#79a4d2; border: 1px solid #79a4d2;}
    </style>
     <script language="javascript">
   function popupDetail(){
        alert("로그아웃 되었습니다.");
        }


  </script>
</head>
 <header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="{% url 'home:homePage' %}"><img src="{% static 'img/mirime.png' %}" alt="" /></a>
          <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">

               <!-- 변경 -->
                  <li class="nav-item">
                        {% if not request.user.is_authenticated %}
                        <a class="nav-link" href="/user/create/">가입하기</a>
                        {% endif %}
                  </li>
                  <li class="nav-item">
                        {% if user.is_active %}
                        <div class="dropdown">
                          <a class="nav-link" href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <i class="fa fa-caret-down"></i>
                        <div class="dropdown-content">
                          <a href="/resume/">자기소개서 입력</a>
                            <a href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <a href="{% url 'mbti_test' %}">MBTI 검사하기</a>
                          <a href="{% url 'home:result_list' %}">면접결과 보기</a>
                           <a id="button" href="/user/logout/" onclick="popupDetail();">로그아웃</a>
                        </div>
                       </div>
                         <li class="nav-item">
                  <a class="nav-link" href="/bot/">면접 진행하기</a>
                </li>
                        {% else %}
                        <a class="nav-link" href="/user/login/">로그인</a>
                        {% endif %}
                  </li>
                  <!-- 변경 -->

                <li class="nav-item">
                  <a class="nav-link" href="/home/#thebookclub">면접챗봇이란?</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:details' %}">상세정보</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/home/#reviewArea">면접후기</a>
                </li>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/article/">게시판</a>
                </li>
              </ul>
            </div>
        </div>
      </nav>
    </div>
  </header>
  <!--================Home Banner Area =================-->
  <section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <div class="banner_content text-center"><br><br><br>
              <h1>Review & Sharing</h1>
              <div class="page_link">
                <a href="#">생생한 면접 후기와 노하우를 공유하세요!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Home Banner Area =================-->

  <!--================ Start Course Details Area =================-->
  <section class="course_details_area section_gap">
    <div class="container">
        {% block css %}
<style type="text/css">
    tbody > tr {cursor: pointer;}
</style>
{% endblock css %}

        {% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
  {{ message }}
</div>
{% endfor %}
{% endif %}

<table width="1000" class="table table-hover" >
    <thead>
        <th style="color: black;">번호</th><th style="color: black;">제목</th><th style="color: black;">작성자</th>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr onclick="location.href='/article/{{ article.pk }}/'">  <!-- 테이블 행 click 시 url 이동 -->
            <td>{{ article.pk }}</td><td>{{ article.title }}</td><td>{{ article.author }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- 버튼 click 시 url 이동 -->
<a href="/article/create/"><button class="button" type="button" >새 게시글 작성</button></a>
                  </div>
 <div class="float-event lvTest" id="testFab">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="my-float">자신의 개성이 반영된 자기소개서입력 완료!<br> 이제 면접만 남았다면 지금 바로 면접을 진행해 보세요!</p>
        </div>
        <div class="col">
          <a href="/bot/"><button class="event-btn" id="finally3" style="margin-top: 16px;" >면접 진행하기</button>
        </div>
      </div>
    </div>
  </div>
  </section>
  <!--================ End Course Details Area =================-->
{% endblock %}

Clustering Resume/Clustering Resume/article/templates/article_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}면접챗봇 | 자기소개서기반 모의면접{% endblock %}
{% block description %}<meta name="description" content="자기소개서를 기반으로 질문을 하는 면접챗봇입니다.">{% endblock %}
{% block content %}
<head>
    <style>
.dropdown .nav-link{
  border: none;
  outline: none;
  background-color: inherit;
  margin: 0;
}
.dropdown-content {
  display: none;
  position: absolute;
  background-color: white;
  min-width: 120px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  font-size : 14px;
  float: none;
  color: black;
  padding: 8px 4px;
  display: block;
  text-align: left;
    border-bottom: 1px solid  black;
}
.dropdown-content a:hover {
  color:#fdc632;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.button{
  width: 20%;
  height: 50px;
  font-family: 'Roboto', sans-serif;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 2.5px;
  font-weight: 500;
  color: white;
  background-color: #79a4d2;
  border: none;
  border-radius: 45px;
  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease 0s;
  cursor: pointer;
  outline: none;
  }

.button:hover {
  background-color: white;
  box-shadow: 0px 15px 20px rgba(121,164,210, 0.4);
  color: #000;
  transform: translateY(-7px);
}
th{color:black;}
#finally3 {background: #79a4d2; color: white; border: #79a4d2;}
#finally3:hover {background:white; color:#79a4d2; border: 1px solid #79a4d2;}
    </style>
     <script language="javascript">
   function popupDetail(){
        alert("로그아웃 되었습니다.");
        }
  </script>
</head>
 <header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="{% url 'home:homePage' %}"><img src="{% static 'img/mirime.png' %}" alt="" /></a>
          <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">

               <!-- 변경 -->
                  <li class="nav-item">
                        {% if not request.user.is_authenticated %}
                        <a class="nav-link" href="/user/create/">가입하기</a>
                        {% endif %}
                  </li>
                 <li class="nav-item">
                        {% if user.is_active %}
                        <div class="dropdown">
                          <a class="nav-link" href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <i class="fa fa-caret-down"></i>
                        <div class="dropdown-content">
                          <a href="/resume/">자기소개서 입력</a>
                            <a href="{% url 'home:mypage' %}">내 정보 보기</a>
                            <a href="{% url 'mbti_test' %}">MBTI 검사하기</a>
                          <a href="{% url 'home:result_list' %}">면접결과 보기</a>
                           <a id="button" href="/user/logout/" onclick="popupDetail();">로그아웃</a>
                        </div>
                       </div>
                        <li class="nav-item">
                  <a class="nav-link" href="/bot/">면접 진행하기</a>
                </li>
                        {% else %}
                        <a class="nav-link" href="/user/login/">로그인</a>
                        {% endif %}
                  </li>
                  <!-- 변경 -->

                <li class="nav-item">
                  <a class="nav-link" href="/home/#thebookclub">면접챗봇이란?</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:details' %}">상세정보</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/home/#reviewArea">면접후기</a>
                </li>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/article/">게시판</a>
                </li>
              </ul>
            </div>
        </div>
      </nav>
    </div>
  </header>
  <!--================Home Banner Area =================-->
  <section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <div class="banner_content text-center"><br><br><br>
              <h1>Review & Sharing</h1>
              <div class="page_link">
                <a href="#">생생한 면접 후기와 노하우를 공유하세요!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Home Banner Area =================-->

  <!--================ Start Course Details Area =================-->
  <section class="course_details_area section_gap">
    <div class="container">
		{% block css %}
{% endblock css %}

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}

<form action="." method="post" class="form-horizontal">
{% csrf_token %}
<input type="hidden" name="action" value="{% if article %}update{% else %}create{% endif %}">
<!--<input type="hidden" name="action" value="{% if article %}update{% else %}create{% endif %}">-->
<table class="table table-striped table-bordered">
	<tr>
		<th>번호</th>
		<td>{{ article.pk }}</td>
	</tr>
	<tr>
		<th>제목</th>
		<td><input type="text" class="form-control" name="title" value="{{ article.title }}"></td>
	</tr>
	<tr>
		<th>내용</th>
		<td><textarea rows="10" class="form-control" name="content">{{ article.content }}</textarea></td>
	</tr>
    <tr>
		<th>작성자</th>
		<td><input type="text" class="form-control" name="author" value="{{ article.author }}"></td>
	</tr>
    <tr>
		<th>작성일</th>
		<td>{{ article.created_at | date:"Y-m-d H:i" }}</td>
	</tr>
</table>

<button class="button" type="submit">저장하기</button>
<a href="/article/"><button class="button" type="button" >목록으로</button></a>
</form>

                  </div>
 <div class="float-event lvTest" id="testFab">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="my-float">자신의 개성이 반영된 자기소개서입력 완료!<br> 이제 면접만 남았다면 지금 바로 면접을 진행해 보세요!</p>
        </div>
        <div class="col">
          <a href="/bot/"><button class="event-btn" id="finally3" style="margin-top: 16px;" >면접 진행하기</button>
        </div>
      </div>
    </div>
  </div>
  </section>
  <!--================ End Course Details Area =================-->
{% endblock %}

Clustering Resume/Clustering Resume/article/templates/base.html
<!-- bbs/templates/base.html -->


<!DOCTYPE html>
<html lang="ko">
    <head>
        {% block title %}
        <title>bbs - minitutorial</title>
        {% endblock title %}

        {% block meta %}
        {% endblock meta %}

        {% block scripts %}
        {% endblock scripts %}

        {% block css %}
        {% endblock css %}
    </head>
    <body>
    {% block header %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/article/">게시글 목록</a>
            </div>
        </div>
    </nav>
    {% if messages %}    <!-- 추가된 부분 시작 -->
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}          <!-- 추가된 부분 끝 -->
    {% endblock header %}

    {% block content %}
    {% endblock content %}
    </body>
</html>